name: CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        echo Packaging up plugin
        zip nymea-plugin-jstest.npk -xi *
